---
- hosts: all
  name: Install Laravel Project
  gather_facts: true
  vars_files:
    - ./vars/main.yml
    - ./vars/artisan_commands.yml
    
  pre_tasks:
    - name: add fpm containers to inventory
      include: ./container_inventory.yml
  tasks:
    - debug: var=ansible_default_ipv4.address
    - debug: var=artisan

    - name: Change permissions
      file:
        dest: "{{ project_root }}/{{project_type.stdout}}/{{project_name.stdout | trim }}/"
        owner: www-data
        group: www-data
        mode: '0777'
        recurse: yes
      become: true

    - name: Composer install
      command: docker exec -it -w {{ project_root }}/{{project_type.stdout}}/{{project_name.stdout | trim }} fpm7.2 composer install
      args:
        chdir: "{{ project_root }}/{{project_type.stdout}}/{{project_name.stdout | trim }}"
      

    - name: Composer require drush 
      command: docker exec -it -w {{ project_root }}/{{project_type.stdout}}/{{project_name.stdout | trim }} fpm7.2 composer require drush/drush
      args:
        chdir: "{{ project_root }}/{{project_type.stdout}}/{{project_name.stdout | trim }}"
      
    - name: Change permissions
      file:
        dest: "{{ project_root }}/{{project_type.stdout}}/{{project_name.stdout | trim }}/"
        owner: www-data
        group: www-data
        mode: '0775'
        recurse: yes
      become: true

    - name: change web directory permissions
      file:
        dest: "{{ project_root }}/{{project_type.stdout}}/{{project_name.stdout | trim }}/web/sites/"
        owner: www-data
        group: www-data
        mode: '0775'
        recurse: yes
      become: true

      
#     - name: create .env 
#       template:
#         src: "templates/{{project_type.stdout}}_env.j2"
#         dest: "{{project_root}}/{{project_type.stdout}}/{{project_name.stdout | trim}}/.env"
#       when: project_type.stdout == "laravel" 
      
#     - name: run composer install
#       delegate_to: "fpm{{php_version}}"
#       raw: sh -c "cd {{project_root}}/{{project_type.stdout}}/{{project_name.stdout | trim}} && composer install"
#       when: project_type.stdout == "laravel" 


#     - name: run artisan
#       delegate_to: "fpm{{php_version}}"
#       raw: sh -c "cd {{project_root}}/{{project_type.stdout}}/{{project_name.stdout | trim}} && php artisan {{ item }}"
#       with_items: 
#         - "{{artisan}}"
#       when: project_type.stdout == "laravel" 

    - name: create nginx conf
      template:
        src: "templates/nginx_{{project_type.stdout}}.j2"
        dest: "{{nginx_config_root}}/{{ project_name.stdout | trim }}.conf"
      
    - debug:
        msg: Nginx Server Name Set to {{ project_name.stdout | trim }}.{{ ansible_default_ipv4.address }}.nip.io
      
    - name: run command in nginx
      delegate_to: web
      raw: nginx -t
      register: nginx_test
      changed_when: false
     
    - debug:
        var: nginx_test
      
    - name: Restart a container
      command: docker restart web
      when: 
      - nginx_test.rc == 0
      changed_when: false
      

# ########################################################################################
# ########################################################################################
